name: Build commons-lib

on:
  push:
    paths:
      - "projects/commons-lib/**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build commons-lib
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Build commons-lib
        run: |
          npm ci
          npm run build commons-lib
