name: Debug Secrets

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Print length of SWA_SHELL_TOKEN
        env:
          TOKEN: ${{ secrets.SWA_SHELL_TOKEN }}
        run: echo "$TOKEN" | wc -c
