name: Deploy mfPayment to Azure Static Web Apps

on:
  push:
    paths:
      - "projects/mf-payment/**"
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy mfPayment
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Build mfPayment
        run: |
          cd mf-payment
          npm ci
          npm run build -- --configuration production

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_MFPAYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "projects/mf-payment"
          output_location: "dist/projects/mf-payment"
